- name: Create a k8s cluster
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    project: smec-build
    auth_kind: serviceaccount
    service_account_file: /srv/key.json
    zone: "europe-west1-b"
    region: "europe-west1"
  tasks:
    - name: create a cluster
      gcp_container_cluster:
        name: "test"
        initial_node_count: 1
        master_auth:
          username: cluster_admin
          password: my-secret-password
        node_config:
          machine_type: n1-standard-2
          disk_size_gb: 100
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: present
