- name: Create a MSql 
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    project: smec-build
    auth_kind: serviceaccount
    service_account_file: /srv/key.json
    zone: "europe-west1-b"
    region: "europe-west1"
  tasks:
    - name: Create an instance
      gcp_sql_instance:
        name: hust_test_123
        region: "{{ region }}"
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: present
