- name: Create a MySql-DB 
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    project: smec-build
    auth_kind: serviceaccount
    service_account_file: /srv/key.json
    zone: "europe-west1-b"
    region: "europe-west1"
  tasks:
    - name: Create a MySql-DB 
      gcp_sql_database:
          name: "{{ mysql_db_name }}"
          charset: utf8mb4
          instance: { "name": "test" }
          project: "{{ project }}"
          auth_kind: "{{ auth_kind }}"
          service_account_file: "{{ service_account_file }}"
          state: present        
