- name: Create a k8s cluster
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    project: smec-build
    auth_kind: serviceaccount
    service_account_file: /srv/key.json
    zone: "europe-west1-b"
    region: "europe-west1"
  tasks:
    - name: create a cluster
      gcp_container_cluster:
        name: "test-cluster"
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: present
      register: cluster
    - name: create a node pool
      gcp_container_node_pool:
        name: "test_nodepool"
        initial_node_count: 1
        autoscaling:
          enabled: true
          max_node_count: 2
          min_node_count: 1
        cluster: "{{ cluster }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        state: present
