---

  - name: Allocate an IP Address
    gcp_compute_address:
      state: present
      name: "{{ ip_name }}"
      region: "{{ region }}"
      project: "{{ project }}"
      auth_kind: "{{ auth_kind }}"
      service_account_file: "{{ service_account_file }}"
      
